
var fs = require('fs');
var yaml = require('js-yaml');

var files = fs.readdirSync('./specs');
for( var x in files ) {
  var file = files[x];
  if( file.substring(file.length - 4) !== '.yml' ) continue;
  var name = file.substring(0, file.length - 4)
  var data = require('./specs/' + file);
  var data2 = {"__ATTN__":"Do not edit this file; changes belong in the appropriate YAML file."};
  for( var y in data ) {
    data2[y] = data[y];
  }
  fs.writeFileSync('./specs/' + name + '.json', JSON.stringify(data2, null, 2));
}
